import Sidebar from "../../components/Sidebar";
import Navbar from "../../components/Navbar";
import StatusBadge from "../../components/StatusBadge";
import AutoRefreshControls from "../../components/AutoRefreshControls";
import LiveUpdateBanner from "../../components/LiveUpdateBanner";
import { api, FaultRecord } from "../../services/api";

export const dynamic = "force-dynamic";


const fallbackFaults: FaultRecord[] = [];


function formatFaultType(faultType: string): string {
  return faultType
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}


function formatTimestamp(timestamp: string): string {
  return new Date(timestamp).toLocaleString();
}


function formatSeverity(severity: string): string {
  return severity.charAt(0).toUpperCase() + severity.slice(1);
}


export default async function Alerts() {
  let faults = fallbackFaults;
  let apiError = false;

  try {
    faults = await api.getFaults(100);
  } catch (error) {
    console.error("Failed to fetch fault data:", error);
    apiError = true;
  }

  return (
    <div className="flex min-h-screen bg-slate-950 text-white">
      <Sidebar />

      <main className="flex-1 p-8">
        <Navbar />

        <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between mb-8">
          <div>
            <h1 className="text-4xl font-bold mb-2">
              Alerts
            </h1>

            <p className="text-slate-400">
              Real V.E.N.U.S fault events generated by substations
            </p>
          </div>

          <div className="flex flex-col items-start md:items-end gap-2">
            <AutoRefreshControls label="Refresh Alerts" />
            <LiveUpdateBanner listenTo={["fault", "prediction"]} />
          </div>
        </div>

        {apiError && (
          <div className="mb-6 rounded-xl border border-red-500/40 bg-red-500/10 p-4 text-red-300">
            <p className="font-semibold">Unable to load alerts</p>
            <p className="text-sm mt-1">
              The backend could not be reached. Make sure the V.E.N.U.S backend is running, then refresh the page.
            </p>
          </div>
        )}

        <div className="space-y-4">
          {faults.length === 0 ? (
            <div className="bg-slate-900 p-5 rounded-xl border border-slate-800 text-slate-400">
              <p className="font-semibold text-slate-300">No fault alerts yet</p>
              <p className="text-sm mt-1">
                Alerts appear here when a fault event is detected. To generate one, inject a fault via the simulator:
              </p>
              <p className="text-sm mt-2 font-mono text-slate-500">
                POST /telemetry/simulate/fault
              </p>
            </div>
          ) : (
            faults.map((fault) => (
              <div
                key={fault.id}
                className="bg-slate-900 p-5 rounded-xl flex justify-between gap-6 border border-slate-800"
              >
                <div>
                  <h2 className="text-lg font-semibold">
                    {formatFaultType(fault.fault_type)}
                  </h2>

                  <p className="text-slate-400">
                    Substation {fault.substation}
                  </p>

                  <p className="text-slate-500 text-sm mt-1">
                    {formatTimestamp(fault.timestamp)}
                  </p>
                </div>

                <StatusBadge status={formatSeverity(fault.severity)} />
              </div>
            ))
          )}
        </div>
      </main>
    </div>
  );
}